### ISSUE TITLE
Support for .twig.html and .json.html

### ISSUE THREAD

**Issue by lubomirblazekcz** [fiadone/vite-plugin-twig#2]
Hi there @fiadone, first of all - great work on your plugin! 

I'm working on a extention for vite named [vituum](https://github.com/vituum/vituum), which would add vite support for various template engines and also with `.twig`, `.json` etc. file exts

I was inspired by your aproach and did a [vite-plugin-latte](https://github.com/lubomirblazekcz/vite-plugin-latte) and added also support for `.latte.html` and `json.html` exts. It works following way https://github.com/lubomirblazekcz/vite-plugin-latte/blob/main/index.js#L73

So you could add similar function for your plugin, with that you don't need to specify `script type="application/json` in the html. And you can adjust your ide settings to treat the file exts as twig or json. But you can still use the script aproach.

I also like your improvements in 2.0, but you should consider adding optionally `data-format="twig"`. If more template engine plugins with this aproach are used, this would help differentiate them from each other. I will do it eventually also in my latte plugin.

Only thing that's kind of disappointing in 2.0 is removing the option to define the template directly in json. I think it's handy, that it can be used to define a layout globally for example here - [https://github.com/vituum/vituum/blob/main/vite.config.js#L17](https://github.com/vituum/vituum/blob/main/vite.config.js#L17)

With these changes your plugin could be used as another optional template engine in vituum. You can take a look here how it works, but it's still a very early work in progress - https://github.com/vituum/vituum/tree/main/playground/views

It would be great if you would consider doing these changes, but if you don't want to, then no problem. I could also wrote a separate twig plugin for vituum.

**Comment by fiadone** [comment]
Hi @lubomirblazekcz, thanks a lot for your interest and appreciation about this plugin! I'm so glad it's inspiring you in having fun with new stuff around the amazing Vite's ecosystem.

Coming to your requests/suggestions:

1.  the _type="application/json"_ on the script tag is not actually required, so you can already omit it if you prefer to handle syntax highlighting in a different way
2. since this plugin is intended to manage twig-based templates only, I think that a _data-format="twig"_ and/or _.twig.html_ are redundant; it may be more interesting instead to extend the plugin configuration with one or more properties defining filters to include/exclude files and scripts to be (or not to be) handled, so you can define yourself any custom way to discriminate the parsing behaviors and also make the plugin compatible with yours and other extensions
3. even if you can certainly configure your IDE and program your logic to treat files as you want, I think that it's anyway a best practice to preserve the validity of a document according to its file extension and not to forget standards; basically, this is the reason why the support for plain json definition inside an html file has been removed in the v2 and that, to be honest, makes me disliking the _.json.html_ approach too

In the next days I'm planning to work on another issue, so I'll try to go deeper with the point 2 and I'll let you know about it ;)

Stay tuned and thanks again!

**Comment by fiadone** [comment]
Hi @lubomirblazekcz, I just released the v2.1.0 of my plugin. Now you can rely on two new configuration options, _fileFilter_ and _fragmentFilter_, thanks to which you'll be able to define your own logic to determine which files and which script fragments should be processed/ignored. You can find a couple of examples [here](https://github.com/fiadone/vite-plugin-twig#filefilter) and [here](https://github.com/fiadone/vite-plugin-twig#fragmentfilter).
Let me know if this update meets your needs so I can close the issue.

**Comment by lubomirblazekcz** [comment]
@fiadone thanks for the changes! This will help :)
